server:
  port: 9201
service-url:
  user-service: http://localhost:8201
spring:
  cloud:
    gateway:
      routes:
        - id: path_route2
          uri: ${service-url.user-service}/user/getByUsername
          predicates:
            - Path=/user/getByUsername
        - id: cookie_route
          uri: ${service-url.user-service}/user/2
          predicates:
            - Cookie=username,ellison
        - id: header_route
          uri: ${service-url.user-service}/user/2
          predicates:
            - Header=X-Request-Id, \d+
        - id: path_route #路由的ID
          uri: ${service-url.user-service}/user/{id} #匹配后路由地址
          predicates: # 断言，路径相匹配的进行路由
            - Path=/user/{id}
        - id: strip_route
          uri: ${service-url.user-service}
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: hystrix_route
          uri: ${service-url.user-service}
          predicates:
            - Method=GET
          filters:
            - name: Hystrix
              args:
                name: facbackcmd
                fallbackUri: forward:/facback



